// Generated by CoffeeScript 1.8.0
(function() {
  var fruit;

  fruit = 'orange';

  if (fruit.length > 5) {
    console.log('The fruit name has more than five characters.');
  } else {
    console.log('The fruit name has less or equal than five characters.');
  }

}).call(this);

//# sourceMappingURL=if.js.map
