// Generated by CoffeeScript 1.8.0
(function() {
  var eat;

  eat = function(food) {
    return food + ' tasted really good.';
  };

  console.log(eat('bananas'));

}).call(this);

//# sourceMappingURL=functions.js.map
