// Generated by CoffeeScript 1.8.0
(function() {
  var pet, pets, _i, _len;

  pets = ['cat', 'dog', 'rat'];

  for (_i = 0, _len = pets.length; _i < _len; _i++) {
    pet = pets[_i];
    pets[_i] = pets[_i] + 's';
  }

  console.log(pets);

}).call(this);

//# sourceMappingURL=arrayloop.js.map
