// Generated by CoffeeScript 1.8.0
(function() {
  var pizzaToppings;

  pizzaToppings = ["tomato sauce", "cheese", "pepperoni"];

  console.log(pizzaToppings);

}).call(this);

//# sourceMappingURL=arrays.js.map
