// Generated by CoffeeScript 1.8.0
(function() {
  var evenNumbers, filtered, numbers;

  numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];

  evenNumbers = function(number) {
    return number % 2 === 0;
  };

  filtered = numbers.filter((function(_this) {
    return function(number) {
      return evenNumbers(number);
    };
  })(this));

  console.log(filtered);

}).call(this);

//# sourceMappingURL=arrayfilter.js.map
