// Generated by CoffeeScript 1.8.0
(function() {
  var pizza;

  pizza = 'pizza is alright';

  console.log(pizza.replace('alright', 'wonderful'));

}).call(this);

//# sourceMappingURL=revisingstrings.js.map
