// Generated by CoffeeScript 1.8.0
(function() {
  var limit, total;

  total = 0;

  limit = 10;

  while (i < limit) {
    total += i;
  }

  console.log(total);

}).call(this);

//# sourceMappingURL=for.js.map
